// Satu-satunya tempat daftar path API backend.
// Ganti base URL di .env; ganti path di sini (satu tempat).
// Aturan: stores/views dilarang menulis string path manual.
export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    profile: '/auth/profile',
  },
  siswa: {
    dashboard: '/dashboard',
    tingkat: '/tingkat',
    pretestMulai: '/pretest',
    pretest: (id) => `/pretest/${id}`,
    pretestJawaban: (id) => `/pretest/${id}/jawaban`,
    pretestSubmit: (id) => `/pretest/${id}/submit`,
    riwayat: '/riwayat',
    materi: '/materi',
    materiDetail: (id) => `/materi/${id}`,
    materiProgress: (id) => `/materi/${id}/progress`,
    quizMulai: (quizId) => `/quiz/${quizId}/mulai`,
    pengerjaan: (id) => `/quiz-pengerjaan/${id}`,
    pengerjaanJawaban: (id) => `/quiz-pengerjaan/${id}/jawaban`,
    pengerjaanSubmit: (id) => `/quiz-pengerjaan/${id}/submit`,
    simulasiSyarat: '/simulasi/syarat',
    simulasi: '/simulasi',
    simulasiMulai: (id) => `/simulasi/${id}/mulai`,
    hasilSimulasi: (id) => `/hasil-simulasi/${id}`,
    hasilSimulasiJawaban: (id) => `/hasil-simulasi/${id}/jawaban`,
    hasilSimulasiSubmit: (id) => `/hasil-simulasi/${id}/submit`,
    hasilSimulasiReview: (id) => `/hasil-simulasi/${id}/review`,
  },
  admin: {
    dashboard: '/admin/dashboard',
    bankSoalKecukupan: '/admin/bank-soal/kecukupan',
    siswa: '/admin/siswa',
    siswaDetail: (id) => `/admin/siswa/${id}`,
    siswaDeactivate: (id) => `/admin/siswa/${id}/deactivate`,
    kompetensi: '/admin/kompetensi',
    kompetensiDetail: (id) => `/admin/kompetensi/${id}`,
    materi: '/admin/materi',
    materiDetail: (id) => `/admin/materi/${id}`,
    materiGambar: '/admin/materi/gambar',
    konteksSoal: '/admin/konteks-soal',
    konteksSoalDetail: (id) => `/admin/konteks-soal/${id}`,
    soal: '/admin/soal',
    soalDetail: (id) => `/admin/soal/${id}`,
    soalPembahasan: (id) => `/admin/soal/${id}/pembahasan`,
    latihan: '/admin/latihan',
    latihanDetail: (id) => `/admin/latihan/${id}`,
    simulasi: '/admin/simulasi',
    simulasiDetail: (id) => `/admin/simulasi/${id}`,
    tingkat: '/admin/tingkat',
    tingkatDetail: (id) => `/admin/tingkat/${id}`,
    aturanPemetaan: (id) => `/admin/tingkat/${id}/aturan-pemetaan`,
  },
}
